### ISSUE TITLE
デプロイエラー

### ISSUE THREAD

**Issue by Annmann3** [Annmann3/sapo-sapuri#155]
```
2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `const_get': uninitialized constant Omniauth::Strategies::Line (NameError)

2023-11-27T13:33:17.227837188Z

2023-11-27T13:33:17.227841478Z parent.const_get(cname, false)

2023-11-27T13:33:17.227845771Z ^^^^^^^^^^

2023-11-27T13:33:17.227849700Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `cget'

2023-11-27T13:33:17.227865500Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'

2023-11-27T13:33:17.227880870Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'

2023-11-27T13:33:17.227885063Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `each'

2023-11-27T13:33:17.227889409Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `ls'

2023-11-27T13:33:17.227893416Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'

2023-11-27T13:33:17.227897219Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'

2023-11-27T13:33:17.227913915Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `each'

2023-11-27T13:33:17.227917852Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'

2023-11-27T13:33:17.227921703Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'

2023-11-27T13:33:17.227925418Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'

2023-11-27T13:33:17.227929406Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:296:in `block in eager_load_all'

2023-11-27T13:33:17.227933123Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `each'

2023-11-27T13:33:17.227954817Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `eager_load_all'

2023-11-27T13:33:17.227959099Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'

2023-11-27T13:33:17.227964137Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'

2023-11-27T13:33:17.227967773Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'

2023-11-27T13:33:17.227971225Z from /sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'

2023-11-27T13:33:17.227974905Z from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'

2023-11-27T13:33:17.227978449Z from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'

2023-11-27T13:33:17.227982181Z from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'

2023-11-27T13:33:17.227985631Z from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'

2023-11-27T13:33:17.227989216Z from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'

2023-11-27T13:33:17.227992580Z from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'

2023-11-27T13:33:17.227995833Z from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'

**Comment by Annmann3** [comment]
**エラー**
```
2023-11-28T02:40:06.978209223Z [e3ae40f5-1b21-434a-af86-d3dbef1b8668] NameError (uninitialized constant Api::LineApiRequest

2023-11-28T02:40:06.978213330Z

2023-11-28T02:40:06.978216898Z @line_api = Api::LineApiRequest.new(user_id)
```

**原因**
`lib/`以下は自動で読み込まれない
`config/application.rb`にautoloadのパスを追加すると本番環境でエラーが起きる
これは本番環境では事前にパスを読み込むため、以下の部分で二重読み込みが発生するから。
https://github.com/Annmann3/sapo-sapuri/blob/fa08ef80b3a79ab3caa9b72a22ec26803f7458c5/config/initializers/omniauth.rb#L1-L4
