### ISSUE TITLE
heroku デプロイのための修正

### ISSUE THREAD

**Issue by Annmann3** [Annmann3/sapo-sapuri#19]
herokuデプロイ周りの対応

**Comment by Annmann3** [comment]
`git heroku main`でエラー
```
ERROR in ./app/javascript/packs/hello_vue.js 10:16-19
"export 'default' (imported as 'Vue') was not found in 'vue'
    at HarmonyImportSpecifierDependency._getErrors (/Users/ak_pc/workspace/portfolio/sapo-sapuri/node_modules/webpack/lib/dependencies/Harm
```
```
remote:        /tmp/build_b5617f77/vendor/bundle/ruby/3.1.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:59:in `block in load'
  1 import { createApp } from 'vue'
remote:        /tmp/build_b5617f77/vendor/bundle/ruby/3.1.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependenc
```
```
Precompiling assets failed.
```

**Comment by Annmann3** [comment]
#23 12f2ac7
で解決
