### ISSUE TITLE
ローカル本番環境でエラー

### ISSUE THREAD

**Issue by Annmann3** [Annmann3/sapo-sapuri#21]
`rails s -e production `
```
=> Booting Puma
=> Rails 6.1.4.6 application starting in production
=> Run `bin/rails server --help` for more startup options
Exiting
/Users/ak_pc/workspace/portfolio/sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require': cannot load such file -- net/pop (LoadError)
        from /Users/ak_pc/workspace/portfolio/sapo-sapuri/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
```

gem `bootsnap`が　`net/pop`を requireできない様子

**Comment by Annmann3** [comment]
`bin/rails assets:precompile RAILS_ENV=production`実行後

```
SassC::SyntaxError: Error: Function rgb is missing argument $green.
        on line 1 of stdin
```
https://github.com/rails/tailwindcss-rails#conflict-with-sassc-rails
tailwindcss のエラー

**Comment by Annmann3** [comment]
1 rails-scss gemを削除
2 bundle
3 `bin/rails tmp:cache:clear`
4 application.scss => application.css

**Comment by Annmann3** [comment]
`bin/rails assets:precompile` 失敗
```
loaderror: cannot load such file sassc
```
