### ISSUE TITLE
Tailwind導入後 bin/webpack でエラーが出る

### ISSUE THREAD

**Issue by Annmann3** [Annmann3/sapo-sapuri#9]
エラー文
```shell
                                     Asset       Size       Chunks                         Chunk Names
    js/application-c5345e19e902946c7faa.js    135 KiB  application  [emitted] [immutable]  application
js/application-c5345e19e902946c7faa.js.map    148 KiB  application  [emitted] [dev]        application
                             manifest.json  364 bytes               [emitted]              
Entrypoint application = js/application-c5345e19e902946c7faa.js js/application-c5345e19e902946c7faa.js.map
[./app/javascript/channels sync recursive _channel\.js$] ./app/javascript/channels sync _channel\.js$ 160 bytes {application} [built]
[./app/javascript/channels/index.js] 211 bytes {application} [built]
[./app/javascript/packs/application.js] 530 bytes {application} [built]
[./app/javascript/stylesheets/application.css] 606 bytes {application} [built]
[./node_modules/css-loader/dist/cjs.js?!./node_modules/postcss-loader/dist/cjs.js?!./app/javascript/stylesheets/application.css] ./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-2!./app/javascript/stylesheets/application.css 630 bytes {application} [built] [failed] [1 error]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 552 bytes {application} [built]
    + 4 hidden modules

ERROR in ./app/javascript/stylesheets/application.css (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-2!./app/javascript/stylesheets/application.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'config'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap?, implementation? }
    at validate (/Users/ak_pc/workspace/portfolio/sapo-sapuri/node_modules/postcss-loader/node_modules/schema-utils/dist/validate.js:105:11)
    at Object.loader (/Users/ak_pc/workspace/portfolio/sapo-sapuri/node_modules/postcss-loader/dist/index.js:43:29)
 @ ./app/javascript/stylesheets/application.css 2:26-170
 @ ./app/javascript/packs/application.js
```

**Comment by Annmann3** [comment]
このエラーについてのissue

https://github.com/rails/webpacker/issues/2784

**Comment by Annmann3** [comment]
postcss-loader バージョン5系にアップグレード
エラー文が変わる


```shell
ℹ ｢wds｣: Project is running at http://localhost:3035/
ℹ ｢wds｣: webpack output is served from /packs/
ℹ ｢wds｣: Content not from webpack is served from /Users/ak_pc/workspace/portfolio/sapo-sapuri/public/packs
ℹ ｢wds｣: 404s will fallback to /index.html
✖ ｢wdm｣: Hash: fb6426a7587accccc8b6
Version: webpack 4.46.0
Time: 1417ms
Built at: 2022/03/09 16:14:54
                                     Asset       Size       Chunks                         Chunk Names
    js/application-bdb267ff78e7eb1ae92c.js    487 KiB  application  [emitted] [immutable]  application
js/application-bdb267ff78e7eb1ae92c.js.map    545 KiB  application  [emitted] [dev]        application
                             manifest.json  364 bytes               [emitted]              

ERROR in ./app/javascript/stylesheets/application.css (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/dist/cjs.js??ref--5-2!./app/javascript/stylesh
eets/application.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (/Users/ak_pc/workspace/portfolio/sapo-sapuri/node_modules/postcss-loader/dist/index.js:38:24)
```
